### ISSUE TITLE
Управление whitelist'ом

### ISSUE THREAD

**Issue by DiSonDS** [VKBots/VBot#27]
- [ ] Реализовать whitelist для команд (будь то пользователь или беседа). Доступ к определенным командам будет только у пользователей/бесед которые в whitelist'е

А так же систему управления whitelist'ом:
- [ ] Добавление/удаление пользователя/беседы командой (для администратора)
- [ ] Просмотр whitelist'а

**Comment by gabbkate** [comment]
Я пока что делаю это вручную.
В settings.py создал elite, в нем id тех кому доступны определенные команды. И в нужных плагинах поставил if uid in elite

**Comment by DlZed** [comment]
Сохраняй в дб
