### ISSUE TITLE
Проверка является ли пользователь участником группы

### ISSUE THREAD

**Issue by Noneeer** [VKBots/VBot#43]
Реализовать проверку является ли пользователь участником группы, при работе от группы, если пользователь не является участником группы - не выполнять команды и предложить вступить, если является то соответственно выполнять команды

**Comment by TiberiumN** [comment]
На самом деле это будет затратной операцией с работой через лонг пуллинг - так как большинство пабликов с такой фичей используют БД для хранения новых и вышедших участников (через Callback API), а уже потом проверяют через ВК АПИ (если в БД этот человек не обнаружен).
Ну а так реализовать можно, правда это не очень красиво будет, так как придётся вставлять код в обработку команды, до её обработки плагинами

**Comment by Myzon** [comment]
Не актуально, теперь запрещено блокировать доступ к боту по правилам ВКонтакте. Если действительно надо - есть простой метод [groups.isMember](https://vk.com/dev/groups.isMember). Через Callback API всё гораздо проще, у пользователей есть атрибут in_group.
