### ISSUE TITLE
При запуске ругается на SocksConnector

### ISSUE THREAD

**Issue by Lis1us** [VKBots/VBot#44]
SocksConnector is not defined

**Comment by TiberiumN** [comment]
@Lis1us https://github.com/VKBots/VBot/issues/37
Проблема не в боте

**Comment by Lis1us** [comment]
@TiberiumN ну он фактически не работает

**Comment by Lis1us** [comment]
@TiberiumN да, форкни себе и поправь там две строчки и всё будет работать

**Comment by TiberiumN** [comment]
@Lis1us как бы у меня уже есть форк. ты не читал ту issue?

**Comment by TiberiumN** [comment]
@Lis1us https://github.com/VKBots/VBot/blob/master/requirements.txt
