### ISSUE TITLE
Ошибка ( на моей стороне ) 

### ISSUE THREAD

**Issue by coyesuten5215125** [VKBots/VBot#53]
File "vbot.py", line 105
    execute += ", ".join((f"{k}: \"" + str(v).replace('"', '\\"') + "\"") for k, v in task.data.items())
                                   ^
SyntaxError: invalid syntax
 ( запуск через python3 )

_____________
  File "vbot.py", line 84
    async def handle_queues(self):
         ^
SyntaxError: invalid syntax
 ( запуск через pypy) 
~~~~~~~~~~
Что делать?

**Comment by TiberiumN** [comment]
Нужен Python 3.6 или PyPy 3.5 (а у вас второй PyPy)

**Comment by coyesuten5215125** [comment]
Я установил И python 3.6   File "vbot.py", line 105
    execute += ", ".join((f"{k}: \"" + str(v).replace('"', '\\"') + "\"") for k, v in task.data.items())
                                   ^
SyntaxError: invalid syntax

**Comment by TiberiumN** [comment]
@coyesuten5215125 покажи, как запускаешь бота
