### ISSUE TITLE
У вас мастербилд сломан

### ISSUE THREAD

**Issue by voron434** [VKBots/VBot#55]
Следите пожалуйста за тем, что коммитите в мастер, у вас не просто так ведь dev  ветка есть :с
  File "vbot.py", line 105
    execute += ", ".join((f"{k}: \"" + str(v).replace('"', '\\"') + "\"") for k, v in task.data.items())
                                   ^
SyntaxError: invalid syntax

**Comment by TiberiumN** [comment]
@voron434 немного грубо отвечу, но.
Как же вы мл*ть надоели-то.В README чёрным по белому написано - Python 3.6 или PyPy3.5, а вы УПОРНО продолжаете пытаться запустить бота на Python 3.5 или на каком-нибудь втором....

**Comment by TiberiumN** [comment]
@voron434 конечно, если вам очень нужно, вы можете добавить поддержку 3.5, заменив все f-строки format'ами или "%". А так же поддержку 3.4, заменив async def на декораторы @asyncio.coroutine.
Но мы этого делать не будем, так как мы не зависим ни от каких старых библиотек, и спокойно можем работать на самой новой версии питона

**Comment by voron434** [comment]
Да, сорян, мой косяк :с
