### ISSUE TITLE
Нельзя установить кодировку для MySQL

### ISSUE THREAD

**Issue by SKYnv** [VKBots/VBot#61]
Нельзя установить кодировку для драйвера.
Драйвер пытается юзать latin-1

  File "/home/skynv/work/.virtualenvs/test/lib/python3.6/site-packages/peewee_async.py", line 1518, in _execute_query_async
    return (yield from _run_sql(query.database, *query.sql()))
  File "/home/skynv/work/.virtualenvs/test/lib/python3.6/site-packages/peewee_async.py", line 1506, in _run_sql
    yield from cursor.execute(operation, *args, **kwargs)
  File "/home/skynv/work/.virtualenvs/test/lib/python3.6/site-packages/aiomysql/cursors.py", line 239, in execute
    yield from self._query(query)
  File "/home/skynv/work/.virtualenvs/test/lib/python3.6/site-packages/aiomysql/cursors.py", line 460, in _query
    yield from conn.query(q)
  File "/home/skynv/work/.virtualenvs/test/lib/python3.6/site-packages/aiomysql/connection.py", line 396, in query
    sql = sql.encode(self.encoding, 'surrogateescape')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 85-88: ordinal not in range(256)

**Comment by SKYnv** [comment]
Хардкод не выход.
```
    @asyncio.coroutine
    def query(self, sql, unbuffered=False):
        # logger.debug("DEBUG: sending query: %s", _convert_to_str(sql))
        if isinstance(sql, str):

            **sql = sql.encode('utf8', 'surrogateescape')**
        yield from self._execute_command(COMMAND.COM_QUERY, sql)
        yield from self._read_query_result(unbuffered=unbuffered)
        return self._affected_rows
```

**Comment by Myzon** [comment]
Не знаю в чём проблема, mysql не использую, таких проблем не встречал. Решите - обязательно напишите, как решили c:

**Comment by SKYnv** [comment]
Так вот и я не использую. С постгресом все норма, а мускуль нужно charset задать, потому что иначе он дефолтный пытается подтянуть (видимо системный, не смотрел код дальше).

Решать наверно выпилом SQL вообще и ioredis в путь ))

**Comment by SKYnv** [comment]
Фикс это

pymysql/connections.py
строка 105
--- DEFAULT_CHARSET = 'latin1'
+++DEFAULT_CHARSET = 'utf8'`

**Comment by Myzon** [comment]
На данный момент латин - это общепринятая практика. В вботе можно как аргумент к базе передавать в database.py, обязательно поправим в следующей версии
