### ISSUE TITLE
Отправка документа.

### ISSUE THREAD

**Issue by SKYnv** [VKBots/VBot#63]
Подскажите как картинку отправить в атачменте не картинкой а документом. Вроде по аналогии с атачментов в виде картинке не получается. Сервер для загрузки не удается получить (запрос вроде правильный)

**Comment by TiberiumN** [comment]
Без кода вам никто не сможет помочь, мы не экстрасенсы

**Comment by SKYnv** [comment]
https://github.com/VKBots/VBot/compare/master...SKYnv:docs_upload

вот, реализовал, но сделал только для группы и для документа картинки. Что-то допилить или так примете?

**Comment by TiberiumN** [comment]
@SKYnv а от пользователя?

**Comment by SKYnv** [comment]
ну мне от пользователя не нужно да и нет у меня лишнего ), но там не нужен параметр Group_id и аплоад серв получается по запросу docs.getUploadServer
Все остальное также вроде.
Если у кого есть желание проверить то милости прошу.

**Comment by TiberiumN** [comment]
@SKYnv ну если ты добавишь работу от юзера и сделаешь пулл реквест, мы конечно же проверим код и смерджим, если всё хорошо)

**Comment by Myzon** [comment]
см, https://github.com/VKBots/VBot/blob/vbot-v6.0/vkplus.py#L153
